### ISSUE TITLE
The cmd window just shuts down as soon as i enter username.

### ISSUE THREAD

**Issue by Shyamalp16** [Khanejo/Instagram-mass-reporter#3]

**Comment by Khanejo** [comment]
Bro the bot works well on both Ubuntu 18.04/16 and Windows 10/7 OS. 

Can you send detailed logs of the error?? Or else you can try to run bot on some other machine or virtual box or online sandbox!!!

**Comment by Khanejo** [comment]
You can use PythonEverywhere for the online free environment solution !!!!
