### ISSUE TITLE
Program Problem

### ISSUE THREAD

**Issue by PatatoFire69** [Khanejo/Instagram-mass-reporter#6]
Everytime I open the program, it crashes. I don't think it's working

**Comment by Khanejo** [comment]
> Everytime I open the program, it crashes. I don't think it's working

Sir, there can be numerous reasons for that like using a depreciated version of selenium, incompatibility of browser drivers,..etc. If you can share the complete error log, then we can try to figure out the problem and then the solution.

**Comment by PatatoFire69** [comment]
Where would I be able to find the error log?

**Comment by Khanejo** [comment]
Import pdb {The Python Debugger} and debug the code until you see some error log/message.

**Comment by Khanejo** [comment]
> Where would I be able to find the error log?

Import pdb {The Python Debugger}, and then just debug through the code until you see some error log/message.

**Comment by YesPaul** [comment]
Why it says there is a 64bits problem compatibily ?

**Comment by Gerykehh** [comment]
howww can i start it??
