### ISSUE TITLE
List out-of-bound

### ISSUE THREAD

**Issue by Stephendron** [Khanejo/Instagram-mass-reporter#7]
Hi,

I've been trying to use this program, and I am getting this error message:

`line 38, in <module>
    pw = file[1]
IndexError: list index out of range`

I am putting the accounts in the acc.txt file in username : password format, but this is still not working
Any suggestions would be much appreciated

Thank you

EDIT: 
Do you think that line 29:
`file = [s.rstrip()fro s in a]`
could possibly be made into a lambda do to this, or is this the correct implementation?

**Comment by Khanejo** [comment]
Sir, it's working properly, you can try to replace it with lambda function but that wouldn't make much difference.{according to me}

Most probably the problem could be with the list formatting only.
