### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sabalandanaei** [Khanejo/Instagram-mass-reporter#9]
PS C:\Users\danaei> & C:/Users/danaei/AppData/Local/Microsoft/WindowsApps/python.exe "a:/Mass/Instagram-mass-reporter-master/Instagram Report Bot2.py"
Username: lillano
Traceback (most recent call last):
  File "a:\Mass\Instagram-mass-reporter-master\Instagram Report Bot2.py", line 38, in <module>
    pw = file[1]
IndexError: list index out of range

**Comment by sabalandanaei** [comment]
Would be nice if you could help me, I am seriously not the best at Python

**Comment by benbangli78** [comment]
Why closing the issue without providing a solution?
